# Generated by Django 5.2 on 2025-04-24 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0002_alter_productmodel_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='ExpenseModel',
        ),
    ]
