# Generated by Django 5.2 on 2025-04-24 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0003_rename_productmodel_expensemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='naming',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='supplier',
            field=models.CharField(default='Maggie', max_length=50),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.CharField(default='No Cat', max_length=100),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qp_app.paymenttype'),
        ),
    ]
