# Generated by Django 5.2 on 2025-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0006_category_supplier_alter_expensemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.CharField(default='No Cat', max_length=100),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='supplier',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
