# Generated by Django 5.2 on 2025-04-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0007_alter_expensemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qp_app.category'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qp_app.supplier'),
        ),
    ]
