# Generated by Django 5.2 on 2025-04-24 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0008_alter_expensemodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_purchases',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
