# Generated by Django 5.2 on 2025-04-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0013_rename_company_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='paymenttype',
            old_name='name',
            new_name='type_name',
        ),
    ]
