# Generated by Django 5.2 on 2025-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0015_rename_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overdue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
