# Generated by Django 5.2 on 2025-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qp_app', '0019_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
